### Check server
GET http://localhost:5000/

### Retrieve all aplications
GET http://localhost:5000/applications

### Retrieve an aplications by id
GET http://localhost:5000/applications/5

### Post an aplications
POST http://localhost:5000/applications
Content-Type: application/json

{
  "company": "Amazon",
  "role": "Data Engineering Intern",
  "location": "US / Remote",
  "job_url": "https://example.com/job",
  "status": "applied",
  "deadline_date": "2026-08-20",
  "applied_date": "2026-08-19",
  "next_action_text": "Wait for the response",
  "next_action_date": null,
  "notes": "Found through website"
}